# Generated by Django 5.1.1 on 2024-09-10 23:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceDirectory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number_of_people', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='RESERVED', max_length=9)),
                ('reservation_name', models.CharField(max_length=80)),
                ('booking_date', models.DateTimeField()),
                ('length_of_stay', models.DurationField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='serviceDirectory.service')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
    ]
