# Generated by Django 5.1.1 on 2024-09-14 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_reservation_length_of_stay_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_name',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='services', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
