# Generated by Django 5.1.1 on 2024-09-11 00:02

import apps.serviceDirectory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceDirectory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=apps.serviceDirectory.models.header_images_directory),
        ),
    ]
