# Generated by Django 5.1.1 on 2024-09-11 00:25

import apps.serviceDirectory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceDirectory', '0002_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='menu',
            field=models.FileField(blank=True, null=True, upload_to=apps.serviceDirectory.models.menu_service_directory),
        ),
    ]
