# Generated by Django 5.1.1 on 2024-09-12 05:19

import apps.serviceDirectory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceDirectory', '0003_alter_service_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_display',
            field=models.ImageField(default='', upload_to=apps.serviceDirectory.models.category_image_directory),
            preserve_default=False,
        ),
    ]
